/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Arcade.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Arcade(props) {
  const { nodes, materials } = useGLTF('/Arcade.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube_5.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube_6.geometry} material={materials['Material.006']} />
    </group>
  )
}

useGLTF.preload('/Arcade.glb')
