/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 me.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function MeModel({animation, ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/me.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names} = useAnimations(animations, group)

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" position={[0, 0.916, 0.29]}>
          <primitive object={nodes.Bone} />
          <group name="Cube001">
            <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.011']} skeleton={nodes.Cube002_1.skeleton} />
            <skinnedMesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials.skin} skeleton={nodes.Cube002_2.skeleton} />
            <skinnedMesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials['Material.001']} skeleton={nodes.Cube002_3.skeleton} />
            <skinnedMesh name="Cube002_4" geometry={nodes.Cube002_4.geometry} material={materials['Material.012']} skeleton={nodes.Cube002_4.skeleton} />
          </group>
          <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} skeleton={nodes.Cube002.skeleton} />
          <skinnedMesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.003']} skeleton={nodes.Cube003.skeleton} />
          <skinnedMesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.002']} skeleton={nodes.Cube004.skeleton} />
          <group name="Plane006">
            <skinnedMesh name="Plane006_1" geometry={nodes.Plane006_1.geometry} material={materials['Material.001']} skeleton={nodes.Plane006_1.skeleton} />
            <skinnedMesh name="Plane006_2" geometry={nodes.Plane006_2.geometry} material={materials['Material.011']} skeleton={nodes.Plane006_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/me.glb')
