/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 nioLight.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function NionLightModel(props) {
  const { nodes, materials } = useGLTF('/nioLight.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane012.geometry} material={materials['Material.003']}>
        <meshStandardMaterial emissive="red" emissiveIntensity={20}/>
      </mesh>
      <mesh geometry={nodes.Plane012_1.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Plane012_2.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Plane012_3.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Plane012_4.geometry} material={materials['Material.009']} />
    </group>
  )
}

useGLTF.preload('/nioLight.glb')
