/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 planet1test.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet1TestModel(props) {
  const { nodes, materials } = useGLTF('/planet1test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere003.geometry} material={materials.about} position={[-0.9, 0, 0]} />
      <mesh geometry={nodes.orbet.geometry} material={nodes.orbet.material} />
    </group>
  )
}

useGLTF.preload('/planet1test.glb')
