/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 planetsfive.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { BallCollider } from '@react-three/rapier'

export function Planet5Model(props) {
  const { nodes, materials } = useGLTF('/planetsfive.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere005.geometry} material={materials.Material} position={[4.297, 0, 0.017]} rotation={[2.956, 0.27, -3.041]} scale={1.856}
        onClick={() => { console.log("Five") }}
      />
      <mesh geometry={nodes.BézierCircle003.geometry} material={materials['Material.001']} scale={[4.332, 0.963, 4.332]} />
    </group>
  )
}

useGLTF.preload('/planetsfive.glb')
