/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Projectdisplay.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ProjectdisplayModel(props) {
  const { nodes, materials } = useGLTF('/Projectdisplay.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.006, 1.048, -0.002]} scale={0.328}>
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Plane004_3.geometry} material={materials['Material.017']} />
      </group>
      <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.014']} />
    </group>
  )
}

useGLTF.preload('/Projectdisplay.glb')
