/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 projects.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ProjectMapModel(props) {
  const { nodes, materials } = useGLTF('/projects.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.247, 4.295, 0.167]} scale={[2.027, 4.078, 2.027]}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.010']} position={[0, 1.131, 0]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.010']} position={[0, 1.131, 0]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.010']} position={[0, 1.131, 0]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.010']} position={[0, 1.131, 0]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.010']} position={[0, 1.131, 0]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.010']} position={[0, 1.131, 0]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['Material.017']} position={[-14.574, 4.103, -16.593]} rotation={[1.585, -0.024, -0.544]} scale={0.34} />
      <mesh geometry={nodes.Plane012.geometry} material={materials['Material.017']} position={[-14.156, 4.145, -16.845]} rotation={[1.585, -0.024, -0.544]} scale={0.34} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['Material.017']} position={[-13.657, 4.105, -17.148]} rotation={[1.585, -0.024, -0.544]} scale={0.34} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['Material.017']} position={[-12.464, 4.051, -18.242]} rotation={[1.568, -0.018, -0.796]} scale={0.34} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['Material.017']} position={[-12.464, 4.051, -18.242]} rotation={[Math.PI / 2, 0, -0.853]} scale={0.34} />
      <mesh geometry={nodes.Plane016.geometry} material={materials['Material.017']} position={[-12.464, 4.051, -18.242]} rotation={[Math.PI / 2, 0, -0.853]} scale={0.34} />
      <group position={[-12.464, 4.051, -18.242]} rotation={[Math.PI / 2, 0, -0.853]} scale={0.34}>
        <mesh geometry={nodes.Plane028.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane028_1.geometry} material={materials['Material.017']} />
      </group>
      <mesh geometry={nodes.Plane018.geometry} material={materials['Material.017']} position={[-11.708, 4.085, -19.144]} rotation={[Math.PI / 2, 0, -1.113]} scale={0.34} />
      <mesh geometry={nodes.Plane019.geometry} material={materials['Material.017']} position={[-11.535, 4.064, -19.494]} rotation={[Math.PI / 2, 0, -1.113]} scale={0.34} />
      <mesh geometry={nodes.Plane021.geometry} material={materials['Material.017']} position={[-11.33, 4.2, -19.91]} rotation={[Math.PI / 2, 0, -1.113]} scale={0.34} />
      <mesh geometry={nodes.Plane022.geometry} material={materials['Material.017']} position={[-11.144, 4.087, -20.288]} rotation={[Math.PI / 2, 0, -1.113]} scale={0.34} />
      <group position={[-20.921, 3.876, 8.377]} rotation={[Math.PI / 2, 0, -2.918]} scale={0.744}>
        <mesh geometry={nodes.Plane039.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane039_1.geometry} material={materials['Material.017']} />
      </group>
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Plane_4.geometry} material={materials.glass} />
      <mesh geometry={nodes.Plane_5.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Plane_6.geometry} material={materials['Material.012']} />
    </group>
  )
}

useGLTF.preload('/projects.glb')
