/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 projects.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ProjectMapModel(props) {
  const { nodes, materials } = useGLTF('/projects.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.247, 4.295, 0.167]} scale={[2.027, 4.078, 2.027]}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Plane_4.geometry} material={materials.glass} />
      <mesh geometry={nodes.Plane_5.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Plane_6.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Plane_7.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Plane_8.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Plane_9.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Plane_10.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Plane_11.geometry} material={materials['Material.012']} />
    </group>
  )
}

useGLTF.preload('/projects.glb')
