/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spaceship-chair.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ChairModel(props) {
  const { nodes, materials } = useGLTF('/spaceship-chair.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.423, 2.623, 19.109]} rotation={[0, 0.461, 0]} scale={1.65}>
        <mesh geometry={nodes.Plane028.geometry} material={materials.walls} />
        <mesh geometry={nodes.Plane028_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane028_2.geometry} material={materials.spacefloor} />
        <mesh geometry={nodes.Plane028_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Plane028_4.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Plane028_5.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane028_6.geometry} material={materials['Material.010']} />
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship-chair.glb')
