/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spaceship.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function SpaceshipModel({animation, ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/spaceship.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions , names} = useAnimations(animations, group)

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 6.105, -14.522]}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Material} skeleton={nodes.Plane.skeleton} />
          <skinnedMesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.sides} skeleton={nodes.Plane001.skeleton} />
          <skinnedMesh name="Plane002" geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} skeleton={nodes.Plane002.skeleton} />
          <skinnedMesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.sides} skeleton={nodes.Plane003.skeleton} />
          <skinnedMesh name="Plane004" geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} skeleton={nodes.Plane004.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship.glb')
