/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tree_1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TreeModel(props) {
  const { nodes, materials } = useGLTF('/tree_1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.03, 1.761, -1.154]} rotation={[1.236, -0.544, 0.204]} scale={0.095}>
        <mesh geometry={nodes.Icosphere023_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Icosphere023_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Icosphere023_3.geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree_1.glb')
