/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Workingplanetmap.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WorkingplanetmapModel(props) {
  const { nodes, materials } = useGLTF('/Workingplanetmap.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.507, 0.547, -3.927]}>
        <mesh geometry={nodes.Icosphere024.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Icosphere024_1.geometry} material={materials['Material.011']} />
      </group>
      <group position={[9.77, 0.297, 5.269]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 9.382]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 13.666]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 17.779]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 22.106]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -24.411]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -20.298]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -16.014]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -11.901]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -7.574]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 7.425]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 11.538]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 15.822]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 19.935]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, 24.262]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -22.255]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -18.142]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -13.858]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -9.745]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[9.77, 0.297, -5.418]} rotation={[0, -1.527, 0]} scale={0.525}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.013']} />
      </group>
      <group scale={[40, 1, 25]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.FLOOR} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.WALL} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/Workingplanetmap.glb')
