/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 working_helmet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HelmetModel(props) {
  const { nodes, materials } = useGLTF('/working_helmet.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.952, 0]}>
        <mesh geometry={nodes.Icosphere024.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Icosphere024_1.geometry} material={materials['Material.011']} />
      </group>
    </group>
  )
}

useGLTF.preload('/working_helmet.glb')
