/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 working_sign.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WorinkingSignModel(props) {
  const { nodes, materials } = useGLTF('/working_sign.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.525}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.013']} />
      </group>
    </group>
  )
}

useGLTF.preload('/working_sign.glb')
